GPIO_Handle_t Gpio;
void delay(uint32_t sec);
void Led_Pin_Init(void);
void Push_Button_Init(void);
int wiper_led_On_Low(void);
int wiper_led_On_Mid(void);
int wiper_led_On_High(void);
void car_starts(void);
int wiper_led_Off(void);
void car_Off(void);
